#Whether this mod is enabled or not
enabled = true
#Whether players can deactivate chopping e.g. by sneaking
canChooseNotToChop = true
#Maximum number of log blocks that can be detected to belong to one tree
#Range: 1 ~ 8096
maxTreeBlocks = 320
#Maximum number of leaves blocks that can destroyed when a tree is felled
#Range: 1 ~ 8096
maxLeavesBlocks = 1024
#Whether to destroy leaves when a tree is felled
breakLeaves = true
#Maximum distance from log blocks to destroy non-standard leaves blocks (e.g. mushroom caps) when felling
#Range: 0 ~ 16
maxBreakLeavesDistance = 7
#Method to use for computing the number of chops needed to fell a tree
#Allowed Values: LINEAR, LOGARITHMIC
chopCountingMethod = "LOGARITHMIC"
#Scales the number of chops (rounding down) required to fell a tree; with chopCountingMethod=LINEAR, this is exactly the number of chops per block
#Range: 0.0 ~ 1024.0
chopCountScale = 1.0
#The tag that blocks must have to be considered choppable (default: treechop:choppables)
blockTagForDetectingLogs = "treechop:choppables"
#The tag that blocks must have to be considered leaves (default: treechop:leaves_like)
blockTagForDetectingLeaves = "treechop:leaves_like"
#List of item registry names (mod:item) and tags (#mod:tag) for items that should not chop when used to break a log
choppingToolsBlacklist = ["#forge:saws", "mekanism:atomic_disassembler"]

